# This is a basic workflow to help you get started with Actions

name: run linters

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    env:
      CONAN_YAMLLINT_WERR: 1
      CONAN_PYLINT_WERR: 1
    strategy:
      fail-fast: false
      matrix:
        hook: ["yaml_linter", "recipe_linter"]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"

      - run: "pip3 install conan yamllint packaging pylint==2.10.2 astroid"

      # Runs a single command using the runners shell
      - name: install hook
        run: |
          conan config install https://github.com/conan-io/hooks.git
          conan config set hooks.${{ matrix.hook }}

      # Runs a set of commands using the runners shell
      - name: run lint
        run: |        
          echo "::add-matcher::matcher.json"
          python3 runlint.py ${{ github.event.pull_request.number }}
